# Generated by Buildr 1.4.15, change to your liking
require 'buildr/ide/eclipse'

# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "stacker"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

desc "The Stacker project"
define "stacker" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  manifest["Main-Class"] = "Stacker"
  layout[:source, :main, :java] = "src"
  layout[:source, :main, :scala] = "src"
  layout[:target, :main] = "bin"
  layout[:target, :main, :java] = "bin"
  layout[:target, :main, :scala] = "bin"
  package :jar
  run.using :main => "Stacker"
end

